#pragma once
#define KIRA_RECOVERY_NVS_NAMESPACE "kira_rec"
#define KIRA_RECOVERY_KEY_ACTION "action"
#define KIRA_RECOVERY_KEY_CRASHES "crashes"
#define KIRA_RECOVERY_SD_MOUNT "/sdcard"
#define KIRA_RECOVERY_DIR KIRA_RECOVERY_SD_MOUNT "/kira"
#define KIRA_RECOVERY_UPDATE_FILE KIRA_RECOVERY_DIR "/update.bin"
#define KIRA_RECOVERY_BACKUP_FILE KIRA_RECOVERY_DIR "/backup.bin"
#define KIRA_RECOVERY_EXPECTED_PROJECT "kira_os"
#define KIRA_RECOVERY_CRASH_LOOP_THRESHOLD 3
typedef enum {
 KIRA_RECOVERY_ACTION_NONE=0, KIRA_RECOVERY_ACTION_INSTALL=1,
 KIRA_RECOVERY_ACTION_RESTORE=2, KIRA_RECOVERY_ACTION_STAY=3,
 KIRA_RECOVERY_ACTION_CRASH_LOOP=4,
} kira_recovery_action_t;
